version: '3.7'

services:

  consul:
    image: "consul:latest"
    container_name: consul
    ports:
      - "8500:8500"

  database:
    image: "postgres:13.4-alpine"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:${DATASOURCE_VOLUME}

  keycloak:
    image: "jboss/keycloak:latest"
    container_name: keycloak
    ports:
      - "8484:8484"

  bff:
    image: "${BFF_SERVICE_IMAGE_NAME}:${BFF_SERVICE_IMAGE_TAG}"
    container_name: bff
    build:
      context: bff
    depends_on:
      - consul
      - admin
      - user
    ports:
      - "8081:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

  user:
    image: "${USER_SERVICE_IMAGE_NAME}:${USER_SERVICE_IMAGE_TAG}"
    container_name: user
    build:
      context: user
    depends_on:
      - consul
    ports:
      - "8082:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_DATASOURCE_URL=${USER_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  admin:
    image: "${ADMIN_SERVICE_IMAGE_NAME}:${ADMIN_SERVICE_IMAGE_TAG}"
    container_name: admin
    build:
      context: admin
    depends_on:
      - consul
    ports:
      - "8083:8080"
    links:
      - consul
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

volumes:
  postgres-data: