version: '3.8'

services:

  consul:
    image: "consul:latest"
    container_name: consul
    ports:
      - "8500:8500"

  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:${DATASOURCE_VOLUME}

  keycloak:
    image: "jboss/keycloak:latest"
    container_name: keycloak
    ports:
      - "8484:8484"

  bff:
    image: "${BFF_SERVICE_IMAGE_NAME}:${BFF_SERVICE_IMAGE_TAG}"
    container_name: bff
    build:
      context: bff
    depends_on:
      - consul
    ports:
      - "8080:8080"

  user:
    image: "${USER_SERVICE_IMAGE_NAME}:${USER_SERVICE_IMAGE_TAG}"
    container_name: user
    build:
      context: user
    depends_on:
      - consul
    ports:
      - "8081:8081"

  admin:
    image: "${ADMIN_SERVICE_IMAGE_NAME}:${ADMIN_SERVICE_IMAGE_TAG}"
    container_name: admin
    build:
      context: admin
    depends_on:
      - consul
    ports:
      - "8083:8083"
    links:
      - consul
    environment:
      - SPRING_CONSUL_HOST=consul # TODO Get from consul
      - SPRING_CONSUL_PORT=8500 # TODO Get from consul

volumes:
  postgres-data: