version: '3.7'

services:

  consul:
    image: "consul:latest"
    container_name: consul
    ports:
      - "8500:8500"

  database:
    image: "postgres:13.4-alpine"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:${DATASOURCE_VOLUME}

  recognizer:
    image: "${RECOGNIZER_SERVICE_IMAGE_NAME}:${RECOGNIZER_SERVICE_IMAGE_TAG}"
    container_name: recognizer
    build:
      context: recognizer
    ports:
      - "8088:8080"
    deploy:
      resources:
        limits:
          memory: 900M

  bff:
    image: "${BFF_SERVICE_IMAGE_NAME}:${BFF_SERVICE_IMAGE_TAG}"
    container_name: bff
    build:
      context: bff
    depends_on:
      - consul
      - auth
      - user
    ports:
      - "8079:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_ACCESS_USER_NAME=${BFF_SERVICE_ACCESS_USER_NAME}
      - SPRING_ACCESS_USER_PASSWORD=${BFF_SERVICE_ACCESS_USER_PASSWORD}

  auth:
    image: "${AUTH_SERVICE_IMAGE_NAME}:${AUTH_SERVICE_IMAGE_TAG}"
    container_name: auth
    build:
      context: auth
    depends_on:
      - consul
      - user
    ports:
      - "8078:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_DATASOURCE_URL=${AUTH_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  user:
    image: "${USER_SERVICE_IMAGE_NAME}:${USER_SERVICE_IMAGE_TAG}"
    container_name: user
    build:
      context: user
    depends_on:
      - consul
      - database
    ports:
      - "8077:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_DATASOURCE_URL=${USER_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  account:
    image: "${ACCOUNT_SERVICE_IMAGE_NAME}:${ACCOUNT_SERVICE_IMAGE_TAG}"
    container_name: user
    build:
      context: user
    depends_on:
      - consul
      - database
    ports:
      - "8077:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_DATASOURCE_URL=${ACCOUNT_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  organization:
    image: "${ORGANIZATION_SERVICE_IMAGE_NAME}:${ORGANIZATION_SERVICE_IMAGE_TAG}"
    container_name: user
    build:
      context: user
    depends_on:
      - consul
      - database
    ports:
      - "8077:8080"
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_CONSUL_HOST=consul
      - SPRING_CONSUL_PORT=8500

      - SPRING_DATASOURCE_URL=${ORGANIZATION_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

volumes:
  postgres-data: